### ISSUE TITLE
Serial Mode Dial to Add Trajectories of the same length

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#223]
Eventually, it will be useful to have a setting where we can: 
1) adjust the time duration of the serial trajectory so that every time we "click" it is the same duration. If you listen to the "Todi Palta" you will hear the patterns easy enough (I recommend you practice singing sargam with them, they are great). But they are uneven in length. 

2) Once we add meter and beats, it would be good to have an overlaid "grid" so we can notate/compose tans in an efficient manner. If a beat is 1 second, then the serial tan can be marked as 2x, 4x, 1.5x, etc. Then the serial mode becomes a single click per note, with the end of the trajectory projected rather than "marked."

**Comment by jon-myers** [comment]
@Dard-Neuman Has this been satisfied by the introduction of the meter / pulse stuff? If so, I will close the issue.
