### ISSUE TITLE
Add octaves

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#224]
Also no hurry, but I just started transcribing Tansen Pandey's Todi, and it requires two additional lower octaves.

**Comment by jon-myers** [comment]
They way things are set up now, it just needs one more half octave. (lowest note is now ni; needs to go down to ma, I think, but maybe ni below just to be safe? )

In any case, for pieces such as this, there needs to be a way to enter in specific requirements for making the spectrogram and applying the appropriate sargam lines.

**Comment by jon-myers** [comment]
This should be available in an overhauled version of the way we are currently making spectrogram. Preferably from within the editor.

**Comment by jon-myers** [comment]
Implemented in editor overhaul
