### ISSUE TITLE
Layering Vowel Default Rule

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#241]
For vowels in a continuous line with multiple trajectories, have the next trajectory default to the previous vowel rather than 'a'. Which is to say, 'a' is the default vowel unless otherwise specified. Once otherwise specified, the new vowel becomes the default until a new vowel or consonant is specified (in which case the default again returns to 'a'.)

Problem: if I'm transcribing a long phrase with multiple trajectories that is a syllable with a vowel other than 'a', it gets very ... tedious (:

**Comment by jon-myers** [comment]
Would this only apply for trajectories that are connected to the original trajectory that has a vowel other than 'a' ? What if there is a small silence in between, even an accidental one? 

I'm considering another feature in issue # : The ability to select a bunch of trajectories and update the vowel all together. Would one be preferable to the other? Would it be useful to have both features?

**Comment by jon-myers** [comment]
from Dard: 

On Thu, Feb 15, 2024 at 9:53 AM Jon Myers <[notifications@github.com](mailto:notifications@github.com)> wrote:
Would this only apply for trajectories that are connected to the original trajectory that has a vowel other than 'a' ?


Yes

What if there is a small silence in between, even an accidental one?



Haven’t considered that. My instinct is that this only operates with contiguous trajectories. But we can discuss 
I'm considering another feature in issue # : The ability to select a bunch of trajectories and update the vowel all together. Would one be preferable to the other? Would it be useful to have both features?

I like it

**Comment by jon-myers** [comment]
@Dard-Neuman both are now implemented
