### ISSUE TITLE
Option to Code Segments (Section Division, Phrase Division, perhaps even other segments within)

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#242]
I'll send an email but let's discuss on Thursday. GitHub doesn't 

1) Numerical and/or letter code to abstract from Hindustani with "open ends" to custom
2) Hindustani 

A. Form (this will be determined by the "event" but the coding can branch accordingly
Alap
Jor
Alap-Jhala

B. Composition (Bandish, Gat, Chiz, Dhrupad)
Pre-Chiz Alap
Asthai
Antara
Manja
Abogh
Sanchari
etc (a few more if we align)
Other specify

C. Elaboration/Improvisation
Barhat/Vistar
Bol Banao
Bol Bandt
Aakar
Sargam
Tan
Layakari
etc (a few more if we align)
Other specify

D. Alankar
Gamak
Murkhi
Meend
Sapaat
Zamzama
etc (a few more if we align)
Other specify

**Comment by jon-myers** [comment]
Be able to create Label(s) (or choose from pre-set names) for each different "section" , this would show in the analysis visualizations.

**Comment by jon-myers** [comment]
A and B seem like they are labels that belong at the "section" level, (right?). Maybe C would be something you can apply at the "phrase" level? and D at the "Trajectory" level? (or maybe "group" level?)
