### ISSUE TITLE
Editor goes black

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#244]
Editor goes black at times when I refresh. Description of problem:

1) Begum Akhtar's Babul Mora. I haven't experienced this with other tracks yet.
2) I go on "loop" mode with the speed slowed.
3) I go off loop mode, press escape, and I'm not able to turn the synthesizer knob up (separate problem)
4) I refresh
5) The editor comes up black. The original recording can be heard, but not the synthesis. But the analysis tab shows data

**Comment by jon-myers** [comment]
line 4921 seems to be hitting an error, in EditorComponent.vue

**Comment by jon-myers** [comment]
Seems to be working now ... getting rid of the issues that were causing the scribble ( in `addVowel` and `moveVowel` seems to have alleviated this as well. So, closing.
