### ISSUE TITLE
Instrument Synthesis doesn't always work

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#245]
I rebooted and tried to play Hafiz Ali Khan and the synthesis was scratchy.

Same happened when I tried to demonstrate at Ashwin and Keshav's. Meaning, I don't think it is solved just by rebooting.

**Comment by jon-myers** [comment]
maybe karplus strong audioworklet isn't loading? Or isn't loading fast enough?

**Comment by jon-myers** [comment]
I'm unable to recreate this issue consistently.... (in fact, I can only recreate it very rarely). But a few ideas:

Something to do with Cache?

Add a function that allows the user to "reset audio", which would destroy and reinitiate the `audioContext`, including reloading the various `audioWorklets`. Maybe this would clear things up?

**Comment by jon-myers** [comment]
@Dard-Neuman I have added a 'reset audio' button to the right panel. See if this fixes the audio playback issue?
