### ISSUE TITLE
Delink Linked Trajectories

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#246]
Have an option to disconnect connected trajectories. Sometimes I want to edit a trajectory, but if it is connected to previous and/or subsequent trajectories I have to delete the entire "phrase" and start over.

**Comment by jon-myers** [comment]
Or said another way: when dragging a "dragDot" at the beginning or end, the user needs an option to insert a silence between two trajectories.

**Comment by jon-myers** [comment]
A further potentiality would be to split up _within_ a 6 trajectory.

**Comment by jon-myers** [comment]
as stated in #82, maybe the simplest way to accomplish this would be to right click on a trajectory and allow user to insert a small rest (0.1 s) before or after traj, if it doesn't have silence before or after.

**Comment by jon-myers** [comment]
@Dard-Neuman you can now right-click on a trajectory and (if applicable) select "insert silence left" or "insert silence right"
