### ISSUE TITLE
Section Analyzer

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#249]
Check out Babul Mora

By my count, there should be 10 sections. It has labels for 4, and heat maps for 10. So perhaps the heat maps are correct, but they are not lining up with the (incomplete) labels.

**Comment by jon-myers** [comment]
For some reason there are multiple entries with the same number for "section starts". This should not be allowed; I'm not sure how they are getting added, but I can make a workaround to get rid of any repetitions when loading the piece / saving the piece.
