### ISSUE TITLE
Trajectory Entry Problem

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#259]
On Abdul Wahid Khan Multani.

When I enter a dot for a trajectory the editor produces two dots, separated by an interval. If I try to add a dot on tivra ni, it will add a dot there AND komal re just above it. 

This is brand new and happened when I started re-transcribing this recording just now.

**Comment by jon-myers** [comment]
I see whats going on and I'm on it. Stand by ...

**Comment by jon-myers** [comment]
should be back to normal now, sorry about that

**Comment by Dard-Neuman** [comment]
Never a need to apologize
