### ISSUE TITLE
deleting section division makes next phrase division into section division

### ISSUE THREAD

**Issue by jon-myers** [jon-myers/idtp#286]
and presumably passes that on to the rest of the transcription as well. 

Need to change the `sectionStarts` property a user deletes these.

**Comment by jon-myers** [comment]
@Dard-Neuman This got fixed; so feel free to update the section divisions (no imperative for this really, just a heads up in case you wanted to...)

**Comment by Dard-Neuman** [comment]
Great, thanks. And will do

**Comment by jon-myers** [comment]
also, @Dard-Neuman , I noticed a bug in the analysis output for the vilayat khan yaman. It was do to the fact that you had drawn a section division at the very end of the piece. This caused bugs, because there were no phrases after this final "section division". Drawing a line at the end like this should be avoided ... the section ends at the end of the piece implicitly. The bold lines don't mark beginnings and endings of sections, they only mark divisions between sections, if that makes sense.

**Comment by Dard-Neuman** [comment]
Got it

I think I was marking a section to transcribe in the future (in case I
waved the white flag on transcribing everything). But if it’s at the very
end it might have been a “typo”
