### ISSUE TITLE
Scale Issue in Shuddha Kalyan (Abdul Karim Khan)

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#333]
1) Shuddh Kalyan has tivra Ma and Tivra Ni as well (same scale as Yaman). 
2) Neither Tivra Ni nor Pa is displaying
3) What is displaying as Dha is Pa (Pa is sounding, but misidentified as Dha).
4) Separate, small thing: but the synthesizer is not picking up the third to last trajectory (I refreshed and it still isn't playing). Update: I just spliced it (added a silence to the left), and it's showing a ghost note if you click on it. I'll leave it alone as I think it's example of me doing something that I'm not allowed to do. So maybe there's something to discover (:
5) In the last trajectory, the IDTP is not allowing me to offset the little dip (from Sa to Dha) to a microtone closer to Sa (it stays put or pops up to Re).

**Comment by jon-myers** [comment]
@Dard-Neuman Not sure how those pitches got left off when I defined the raag. But I redefined it, and made a new transcription. Will have to start over from scratch. Here is the link: https://swara.studio/editor?id=6516ef0d52718608f20f68aa&pIdx=0

**Comment by jon-myers** [comment]
By the way, I think I fixed the issue with the first one, so if you want to go back to using the original, that should work as well.
