### ISSUE TITLE
Adding sections in between

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#339]
I changed a partition coded as a phrase to a section and it didn't "push" the subsequent sections out. Meaning, what is now section 5 has the code of old section 4. It's still called "composition" and it should be "Improvisation". Which we can confirm because the phrase (coded a few days ago), still correctly says barhat (a type of improvisation).

Happy to describe if the above makes no sense. One way to test it is to go to one of your transcriptions, add and name/code 3-4 sections with some phrases. Then add a section in between existing sections (because you transcribed it later or because you realize you missed it before), or change a phrase to a section. See if the subsequent section names/codes carries forward. 

If this turns out to be a reproducible glitch and not my user error, BUT it requires a complicated solve, I'm fine just disciplining myself to add sections sequentially and teleologically, from beginning to end.

**Comment by jon-myers** [comment]
I understand what you are describing, and am seeing the same thing on my end. I will look into it, hopefully not too complicated.
