### ISSUE TITLE
Section bug

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#370]
Abdul Wahid Khan: Multani; Minute 2:40

I'm in the process of "fixing" my old section breaks (where I started them "prior" to the trajectory onset.

With those adjustments thus far, we see section 3 jumps to Section 31 at minute 2:40

**Comment by jon-myers** [comment]
I’m not sure what you mean by this. Maybe you can show me tomorrow?

**Comment by Dard-Neuman** [comment]
The core challenge is that adding or deleting sections/phrases into an already existing transcription doesn't always push or contract the section/phrase coding accordingly.

I've been trying a different technique whereby every time I delete or add a section or phrase into something already transcribed, I not only save but close out and re-enter. That has been helping.

**Comment by Dard-Neuman** [comment]
Don't worry about one for another week. I've been more methodical about my approach, including waiting after I save before doing any additional actions. Let me see if the problem continues and what I did prior to provoke it. I'm guessing that I did multiple actions before letting the program fully save one (or one set of) actions
