### ISSUE TITLE
Instrumental Bols

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#388]
Add option to identify instrumental bols. For sitar, they could be limited to da, ra, diri, dra, rda,

**Comment by jon-myers** [comment]
This is related to #344, but maybe we should discuss. My way of thinking about this, there is just da and ra. Each articulation is either one or the other. But you may be thinking of this differently.

**Comment by jon-myers** [comment]
#344 was closed, but this is still related to #343

**Comment by jon-myers** [comment]
There should be six options for labeling each pluck: da, di, d, ra, ri, r,. Internally, it may make sense for these to index to two states: up stroke and down stroke.

**Comment by jon-myers** [comment]
This really involves a few steps.
1. Adding a dropdown menu option when right-clicking on a pluck. All 6 options will appear, the current one with a checkmark next to it. ('\u2713')
2. Need to update Articulation class to keep track of "stroke nickname". Actual stroke is either "da" or "ra". 
3. Adding a way to display this stuff to the editor. And a checkbox to hide / show this info.

**Comment by jon-myers** [comment]
@Dard-Neuman this has now been implemented. If a traj has a pluck, you can now right click on it to select which stroke you want. Check the "bols" box on the right to display these stroke nicknames.
