### ISSUE TITLE
Different Tracks (within and between musicians)

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#59]
For a single musician:  add feature that adds "tracks"/fields to notate action beyond main/melodic: e.g., jora, sympathetic (tarafs) pluck, reverse (ra) right hand bol, perhaps chikari (which right now occurs in the melodic field), discrete chikari articulations.

For a single musician: vertical tala/rhythmic events 

For multiple melodic musicians 

For percussion

**Comment by jon-myers** [comment]
This is related to, but perhaps even a step beyond issue #31

**Comment by jon-myers** [comment]
this has been implemented
